-- This script is really basic.  It should be OK but use at your own risk.



USE [master]
GO
CREATE DATABASE [SmartMeter]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SmartMeter', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SmartMeter.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SmartMeter_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SmartMeter_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SmartMeter].[dbo].[sp_fulltext_database] @action = 'enable'

ALTER DATABASE [SmartMeter] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SmartMeter] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SmartMeter] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SmartMeter] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SmartMeter] SET ARITHABORT OFF 
GO

ALTER DATABASE [SmartMeter] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SmartMeter] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SmartMeter] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SmartMeter] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SmartMeter] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SmartMeter] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SmartMeter] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SmartMeter] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SmartMeter] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SmartMeter] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SmartMeter] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SmartMeter] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SmartMeter] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SmartMeter] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SmartMeter] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SmartMeter] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SmartMeter] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SmartMeter] SET RECOVERY FULL 
GO

ALTER DATABASE [SmartMeter] SET  MULTI_USER 
GO

ALTER DATABASE [SmartMeter] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SmartMeter] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SmartMeter] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SmartMeter] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SmartMeter] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SmartMeter] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SmartMeter] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SmartMeter] SET  READ_WRITE 
GO


USE [SmartMeter]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Reads](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DT] [datetime] NOT NULL,
	[KWH] [decimal](5, 3) NOT NULL,
	[TimeStart] [time](0) NOT NULL,
	[TimeEnd] [time](0) NOT NULL,
	[ReadDate] [date] NOT NULL,
 CONSTRAINT [PK_Reads] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



USE [master]
GO
declare @password as varchar(20)='pysmtemail123!' -- the default password here is pysmtemail123!.  it is highly recommend you modify this and update your smt_download_config.json accordingly.
declare @createlogin varchar(200)
set @createlogin='CREATE LOGIN [pysmtdownloader] WITH PASSWORD=''' + @password + ''', DEFAULT_DATABASE=[SmartMeter], CHECK_EXPIRATION=ON, CHECK_POLICY=ON'

Exec (@createlogin)
GO
use [master];
GO
USE [SmartMeter]
GO
CREATE USER [pysmtdownloader] FOR LOGIN [pysmtdownloader]
GO
USE [SmartMeter]
GO
ALTER ROLE [db_datareader] ADD MEMBER [pysmtdownloader]
GO
USE [SmartMeter]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [pysmtdownloader]
GO
